name: Fabric CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  buildAndRunForSomeVersions:
    name: Run tests for ${{ matrix.minecraftVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        minecraftVersion:
          - latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: Geometrically/fabric-test-runner@v1
        id: testRunner
        with:
          minecraftVersion: ${{ matrix.minecraftVersion }}
      - name: Upload to Bintray & CurseForge
        run: ./gradlew clean bintrayUpload #curseforge
        env:
          BINTRAY_USER: catcore
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          CURSEKEY: ${{ secrets.CURSEKEY }}
